### ISSUE TITLE
怎么生成about页面

### ISSUE THREAD

**Issue by hlx70375** [twoyao/beautiful-hexo#1]
我用hexo new page “about”
然后运行hexo g会提示错误

```
Unhandled rejection TypeError: /home/dg/dgw/shachuang/themes/beautiful-hexo/layout/partial/post-meta.jade:3
    1| mixin post_meta(date, tags)
    2|     p.post-meta Posted on #{full_date(date, "MMM D YYYY")}
  > 3|         - tags.each(function(tag) {
    4|             = ' · '
    5|             a.tag.post-meta(href=url_for(tag.path))= tag.name
    6|         - })

Cannot read property 'each' of undefined
    at Object.jade_mixins.post_meta.jade_interp [as post_meta] (eval at <anonymous> (/home/dg/dgw/shachuang/node_modules/jade/lib/index.js:218:8), <anonymous>:21:5)
    at eval (eval at <anonymous> (/home/dg/dgw/shachuang/node_modules/jade/lib/index.js:218:8), <anonymous>:344:25)
    at eval (eval at <anonymous> (/home/dg/dgw/shachuang/node_modules/jade/lib/index.js:218:8), <anonymous>:793:22)
    at res (/home/dg/dgw/shachuang/node_modules/jade/lib/index.js:219:38)
    at _compiled (/home/dg/dgw/shachuang/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/dg/dgw/shachuang/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/dg/dgw/shachuang/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/dg/dgw/shachuang/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/dg/dgw/shachuang/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/dg/dgw/shachuang/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:329:10)
    at resume_ (_stream_readable.js:719:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

**Comment by twoyao** [comment]
感谢使用

这个问题已经修复，请pull最新版本。`hexo new page "about"` 会生成"source/about/index.md"

``` yml
title: about
date: 2016-07-13 22:28:32
---
```

也可以额外指定一个副标题

``` yml
title: about
subtitle: "page subtitle"
date: 2016-07-13 22:28:32
---
```
